export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const CLEAR_REGISTRATION = "CLEAR_REGISTRATION";
export const PASSWORD_SUCESSFULLY_CHANGED = "PASSWORD_SUCESSFULLY_CHANGED";
export const CREATE_USED_CAR_FOR_SALE_SUCCESS =
  "CREATE_USED_CAR_FOR_SALE_SUCCESS";
export const USED_CAR_DETAILS = "USED_CAR_DETAILS";
export const GET_USED_CARS = "GET_USED_CARS";
export const USED_CAR_SUGESSTION = "USED_CAR_SUGESSTION";
export const CATEGORIES = "CATEGORIES";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CURRENT_USER_DETAILS = "CURRENT_USER_DETAILS";
